from .schemas import MemoryInput

SAMPLES=[
    {'title':'Pump P-204: vibration after a cold start','body':'At North station, Pump P-204 showed intermittent vibration during cold starts. Isolate the pump and check coupling alignment, mounting bolts and the inlet strainer. Record measurements against the manufacturer limits before returning it to service. This is an illustrative maintenance note, not an approved safety procedure.','category':'Observation','tags':['pump','vibration','cold-start'],'priority':'high','visibility':'team','source':'Demo field observation · Unit 07'},
    {'title':'Safe inspection before opening a valve enclosure','body':'Use the site-approved lockout and tagout procedure before opening the valve enclosure. Verify the isolation with the authorized operator. Follow the equipment manual and record the permit reference in the work order. This demo note is a reminder, not a substitute for an approved procedure.','category':'Procedure','tags':['valve','isolation','inspection'],'priority':'critical','visibility':'team','source':'Illustrative operations checklist'},
    {'title':'A recurring pressure drop on the north water line','body':'The north water line has a recurring pressure drop after filter replacement. Check whether air remains in the line and whether the filter housing seal is seated correctly. Compare readings before and after the inspection. Escalate persistent low pressure to the maintenance lead.','category':'Incident','tags':['pressure','water','filter'],'priority':'high','visibility':'team','source':'Demo incident log'},
    {'title':'Private handover note for the next technician','body':'A field technician left an unverified personal observation about the next shift. Keep this handover on the device until it has been reviewed and rewritten as a team-safe equipment observation.','category':'Observation','tags':['handover','private'],'priority':'normal','visibility':'local','source':'Illustrative private notebook'},
    {'title':'Sensor drift reference: temperature transmitter','body':'A gradual temperature reading shift can indicate sensor drift, connection issues or changing operating conditions. Compare against a calibrated reference following the approved test procedure. Do not assume the sensor is defective from one reading.','category':'Reference','tags':['temperature','sensor','calibration'],'priority':'normal','visibility':'team','source':'Demo knowledge card'},
    {'title':'Restricted contact in a service note','body':'Demo contact only: engineer@example.test. The station contact was included in this observation, so the routing policy keeps it local even when team sharing is selected. Remove contact details before promoting the observation to shared knowledge.','category':'Observation','tags':['contact','privacy'],'priority':'low','visibility':'team','source':'Synthetic privacy-policy example'},
    {'title':'Battery shelf-life checks for remote sensors','body':'During a scheduled inspection, note sensor battery age and operating temperature. Use the vendor guidelines to choose the replacement interval. Retain the last three readings to distinguish a low battery from a communication issue.','category':'Reference','tags':['battery','sensor','remote'],'priority':'low','visibility':'team','source':'Illustrative reference card'},
    {'title':'Field repair: a loose cable connector','body':'A loose connector caused intermittent telemetry on the East station sensor. After isolation under the approved procedure, the technician reseated the connector and documented the result. Confirm stable telemetry and inspect cable strain before closing the work order.','category':'Observation','site':'East station','tags':['telemetry','connector','repair'],'priority':'normal','visibility':'team','source':'Demo repair note'},
]

def seed_device(device):
    for sample in SAMPLES: device.save(MemoryInput(**sample))
